'use client';
import { useEffect, useState } from 'react'; import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query'; import * as Icons from 'lucide-react'; import { X } from 'lucide-react'; import { api } from '@/lib/api'; import type { Envelope } from '@/lib/types';
type Accessory={id:number;name:string;icon:string;image_url?:string|null}; type Avatar={avatar_base:string;equipped_accessory:Accessory|null;available_bases:{code:string;label:string;color:string}[];unlocked_accessories:Accessory[]};
// Converte "hard-hat" ou "avatar_base" pro PascalCase que o lucide-react exporta
// (HardHat, AvatarBase) — precisa cobrir tanto "-" quanto "_" porque os dois
// aparecem nos dados (bases de avatar usam nomes simples, mas alguns ícones de
// colecionável vêm em kebab-case, ex.: "hard-hat").
export const AvatarIcon=({name,className}:{name?:string;className?:string})=>{const key=name?.replace(/(^|[-_])([a-z])/g,(_,__,x)=>x.toUpperCase())||'Compass';const C=(Icons as unknown as Record<string,React.ComponentType<{className?:string}>>)[key]||Icons.Compass;return <C className={className}/>};
export function AvatarVisual({base,accessory}:{base?:string;accessory?:Accessory|null}){return <span className="relative grid h-20 w-20 place-items-center rounded-full bg-sky-100 text-sky-800"><AvatarIcon name={base} className="h-10 w-10"/>{accessory&&<span className="absolute -bottom-1 -right-1 grid h-8 w-8 place-items-center rounded-full bg-amber-300 text-amber-950"><AvatarIcon name={accessory.icon} className="h-4 w-4"/></span>}</span>}
export function AvatarEditor({open,onClose}:{open:boolean;onClose:()=>void}){const client=useQueryClient();const q=useQuery({queryKey:['avatar'],queryFn:()=>api<Envelope<Avatar>>('/api/avatar').then(r=>r.data),enabled:open});const [base,setBase]=useState('compass');const [accessory,setAccessory]=useState<number|null>(null);const data=q.data;
  // Sem isso, base/accessory ficavam sempre no valor inicial (compass/nenhum)
  // mesmo quando o aluno já tinha um avatar salvo — e "Salvar" sem mexer em
  // nada resetava o avatar dele de volta pro padrão sem querer.
  useEffect(()=>{if(data){setBase(data.avatar_base);setAccessory(data.equipped_accessory?.id??null);}},[data]);
  const save=useMutation({mutationFn:()=>api('/api/avatar',{method:'PUT',body:JSON.stringify({avatar_base:base,equipped_accessory_id:accessory})}),onSuccess:()=>{client.invalidateQueries({queryKey:['avatar']});client.invalidateQueries({queryKey:['passport']});client.invalidateQueries({queryKey:['me']});onClose()}});if(!open)return null;return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/65 p-4"><section role="dialog" aria-modal="true" className="w-full max-w-lg rounded-3xl bg-white p-6 text-slate-900"><div className="flex justify-between"><h2 className="text-2xl font-black">Editar avatar</h2><button onClick={onClose}><X/></button></div>{!data?<p className="mt-6">Carregando opções…</p>:<><div className="mt-6 grid grid-cols-3 gap-3">{data.available_bases.map(x=><button key={x.code} onClick={()=>setBase(x.code)} className={`rounded-2xl border-2 p-3 ${base===x.code?'border-sky-600 bg-sky-50':'border-slate-200'}`} style={{color:x.color}}><AvatarIcon name={x.code} className="mx-auto h-7 w-7"/><span className="mt-2 block text-xs font-bold">{x.label}</span></button>)}</div><h3 className="mt-6 font-black">Acessório</h3><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>setAccessory(null)} className="rounded-xl border px-3 py-2">Nenhum</button>{data.unlocked_accessories.map(x=><button key={x.id} onClick={()=>setAccessory(x.id)} className={`rounded-xl border px-3 py-2 ${accessory===x.id?'border-sky-600 bg-sky-50':''}`}><AvatarIcon name={x.icon} className="mr-1 inline h-4 w-4"/>{x.name}</button>)}</div><button onClick={()=>save.mutate()} className="btn-primary mt-7 w-full">Salvar avatar</button></>}</section></div>}
