'use client';
import { useEffect,useState } from 'react'; import { Trophy } from 'lucide-react';
type Collectible={id:number;name:string;category:string;icon:string;image_url?:string|null;rarity:'common'|'rare'|'epic'};type Result={score:number;experience_gained:number;level_up:boolean;achievements_unlocked:{id:number;title:string;icon:string}[];collectibles_unlocked?:Collectible[]};
export function CelebrationScreen({result}:{result:Result}){const score=useCount(result.score),xp=useCount(result.experience_gained);return <main className="relative grid min-h-screen place-items-center overflow-hidden bg-[radial-gradient(circle_at_top,#0ea5e9,transparent_35%),linear-gradient(135deg,#082f49,#0f172a)] p-5 text-white"><div className="confetti">{Array.from({length:28},(_,i)=><i key={i} style={{left:`${i*37%100}%`,animationDelay:`${i%8*110}ms`,backgroundColor:['#fbbf24','#22d3ee','#fb7185'][i%3]}}/>)}</div><section className="relative w-full max-w-xl rounded-[2rem] border border-white/20 bg-white/10 p-8 text-center shadow-2xl backdrop-blur"><div className="celebration-trophy mx-auto grid h-24 w-24 place-items-center rounded-full bg-amber-300 text-amber-950"><Trophy size={48}/></div><p className="mt-6 text-sm font-black tracking-[.25em] text-cyan-200">MISSÃO CONCLUÍDA</p><h1 className="mt-2 text-4xl font-black">Expedição completa!</h1><div className="mt-8 grid grid-cols-2 gap-3"><Metric value={score} label="pontos" color="text-amber-300"/><Metric value={`+${xp}`} label="XP ganho" color="text-cyan-200"/></div>{result.level_up&&<div className="level-up-pop mt-5 rounded-2xl bg-amber-300 p-5 font-black text-amber-950">🎉 Você subiu de nível!</div>}<Reveal title="Conquistas desbloqueadas" items={result.achievements_unlocked.map(x=>({id:x.id,name:x.title,icon:x.icon}))}/><Reveal title="Novos itens da coleção" items={result.collectibles_unlocked??[]}/><a href="/dashboard" className="mt-8 inline-flex rounded-xl bg-white px-6 py-3 font-black text-sky-900">Voltar ao painel</a></section></main>}
function Reveal({title,items}:{title:string;items:{id:number;name:string;icon:string;image_url?:string|null}[]}){if(!items.length)return null;return <div className="mt-6 text-left"><p className="font-black">{title}</p><div className="mt-3 space-y-2">{items.map((x,i)=><div key={x.id} className="achievement-reveal flex items-center gap-3 rounded-xl bg-white/10 p-3" style={{animationDelay:`${400+i*180}ms`}}>{x.image_url?<img src={x.image_url} alt="" className="h-8 w-8 object-contain"/>:<span className="text-2xl">{x.icon||'🏅'}</span>}<span className="font-bold">{x.name}</span></div>)}</div></div>}
function Metric({value,label,color}:{value:string|number;label:string;color:string}){return <div className="rounded-2xl bg-white/10 p-4"><p className={`text-4xl font-black ${color}`}>{value}</p><p className="text-sm text-slate-200">{label}</p></div>};// Respeita prefers-reduced-motion do SO e o toggle de acessibilidade do
// próprio app (lib/ui-store.ts) — sem isso, a contagem animada roda sempre,
// ignorando quem pediu pra reduzir movimento.
function useCount(target:number){const [v,setV]=useState(0);useEffect(()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches||document.documentElement.dataset.motion==='reduce'){setV(target);return;}const s=performance.now();let f=0;const go=(n:number)=>{const p=Math.min(1,(n-s)/1100);setV(Math.round(target*(1-(1-p)**3)));if(p<1)f=requestAnimationFrame(go)};f=requestAnimationFrame(go);return()=>cancelAnimationFrame(f)},[target]);return v}
