'use client';

import { useEffect, useState } from 'react';
import { Trophy } from 'lucide-react';

type Result = { score: number; experience_gained: number; level_up: boolean; achievements_unlocked: { id: number; title: string; icon: string }[] };

export function CelebrationScreen({ result }: { result: Result }) {
  const score = useCountingNumber(result.score); const xp = useCountingNumber(result.experience_gained);
  return <main className="relative grid min-h-screen place-items-center overflow-hidden bg-[radial-gradient(circle_at_top,#0ea5e9,transparent_35%),linear-gradient(135deg,#082f49,#0f172a)] p-5 text-white"><div className="confetti" aria-hidden>{Array.from({ length: 28 }, (_, i) => <i key={i} style={{ left: `${(i * 37) % 100}%`, animationDelay: `${(i % 8) * 110}ms`, backgroundColor: ['#fbbf24', '#22d3ee', '#fb7185', '#a3e635'][i % 4] }} />)}</div><section className="relative w-full max-w-xl rounded-[2rem] border border-white/20 bg-white/10 p-8 text-center shadow-2xl backdrop-blur md:p-12"><div className="celebration-trophy mx-auto grid h-24 w-24 place-items-center rounded-full bg-amber-300 text-amber-950 shadow-[0_0_55px_#fcd34d]"><Trophy size={48} /></div><p className="mt-6 text-sm font-black uppercase tracking-[.25em] text-cyan-200">Missão concluída</p><h1 className="mt-2 text-4xl font-black">Expedição completa!</h1><div className="mt-8 grid grid-cols-2 gap-3"><Metric value={score} label="pontos" color="text-amber-300" /><Metric value={`+${xp}`} label="XP ganho" color="text-cyan-200" /></div>{result.level_up && <div className="level-up-pop mt-5 rounded-2xl bg-amber-300 p-5 font-black text-amber-950">🎉 Você subiu de nível!</div>}{result.achievements_unlocked.length > 0 && <div className="mt-6 text-left"><p className="font-black">Conquistas desbloqueadas</p><div className="mt-3 space-y-2">{result.achievements_unlocked.map((achievement, index) => <div key={achievement.id} className="achievement-reveal flex items-center gap-3 rounded-xl bg-white/10 p-3" style={{ animationDelay: `${400 + index * 180}ms` }}><span className="text-2xl">{achievement.icon || '🏅'}</span><span className="font-bold">{achievement.title}</span></div>)}</div></div>}<a href="/dashboard" className="mt-8 inline-flex rounded-xl bg-white px-6 py-3 font-black text-sky-900">Voltar ao painel</a></section></main>;
}
function Metric({ value, label, color }: { value: string | number; label: string; color: string }) { return <div className="rounded-2xl bg-white/10 p-4"><p className={`text-4xl font-black ${color}`}>{value}</p><p className="text-sm text-slate-200">{label}</p></div>; }
function useCountingNumber(target: number) { const [value, setValue] = useState(0); useEffect(() => { if (window.matchMedia('(prefers-reduced-motion: reduce)').matches || document.documentElement.dataset.motion === 'reduce') { setValue(target); return; } const started = performance.now(); let frame = 0; const animate = (now: number) => { const progress = Math.min(1, (now - started) / 1100); setValue(Math.round(target * (1 - (1 - progress) ** 3))); if (progress < 1) frame = requestAnimationFrame(animate); }; frame = requestAnimationFrame(animate); return () => cancelAnimationFrame(frame); }, [target]); return value; }
