'use client';

import Link from 'next/link';
import { CheckCircle2, Clock, Compass, Lock, MapPin, Sparkles } from 'lucide-react';
import type { Campaign } from '@/lib/types';

export function XpBar({ value = 0, next = 100, level = 'Viajante' }: { value?: number; next?: number; level?: string }) {
  const pct = Math.min(100, next ? value / next * 100 : 0); const dash = 251.2;
  return <section className="game-card relative overflow-hidden p-5"><div className="absolute -right-8 -top-10 h-32 w-32 rounded-full bg-cyan-100/70" /><div className="relative flex items-center gap-5"><div className="relative h-20 w-20 shrink-0"><svg viewBox="0 0 100 100" className="-rotate-90"><circle cx="50" cy="50" r="40" fill="none" stroke="#e0f2fe" strokeWidth="10" /><circle cx="50" cy="50" r="40" fill="none" stroke="#fbbf24" strokeWidth="10" strokeLinecap="round" className="xp-ring" style={{ strokeDasharray: dash, strokeDashoffset: dash * (1 - pct / 100) }} /></svg><Compass className="absolute inset-0 m-auto h-7 w-7 text-sky-800" /></div><div className="min-w-0 flex-1"><div className="flex justify-between gap-2 text-sm"><strong className="text-sky-900">Nível: {level}</strong><span className="font-bold text-slate-600">{value} / {next} XP</span></div><div className="mt-3 h-3 overflow-hidden rounded-full bg-sky-100"><div className="xp-fill h-full rounded-full bg-[linear-gradient(90deg,#f59e0b,#fcd34d,#2dd4bf)]" style={{ width: `${pct}%` }} /></div><p className="mt-2 text-xs font-semibold text-sky-700">Continue a expedição para chegar ao próximo nível.</p></div></div></section>;
}

export function CampaignCard({ campaign }: { campaign: Campaign }) {
  const isComplete = campaign.progress.status === 'completed'; const subjectColor = campaign.primary_subject.color || '#0284c7';
  const pattern = { backgroundColor: subjectColor, backgroundImage: `radial-gradient(circle at 18% 25%, rgba(255,255,255,.35) 0 3px, transparent 4px), radial-gradient(circle at 70% 68%, rgba(255,255,255,.18) 0 2px, transparent 3px), linear-gradient(135deg, ${subjectColor}, #003f6b)` };
  return <article className="campaign-card game-card group overflow-hidden"><div className="relative h-36 overflow-hidden" style={campaign.cover_image_url ? undefined : pattern}>{campaign.cover_image_url && <div className="h-full w-full bg-cover bg-center transition duration-500 group-hover:scale-110" style={{ backgroundImage: `url(${campaign.cover_image_url})` }} />}<div className="absolute inset-0 bg-[linear-gradient(135deg,rgba(0,32,61,.15),rgba(0,68,113,.55))]" /><Compass className="absolute right-5 top-5 h-12 w-12 text-white/45 transition duration-500 group-hover:rotate-45" />{isComplete && <span className="absolute bottom-4 left-4 rounded-full bg-amber-300 px-3 py-1 text-xs font-black text-amber-950 shadow-lg">✓ EXPEDIÇÃO CONCLUÍDA</span>}</div><div className="p-5"><div className="mb-3 flex justify-between gap-2 text-sm"><span className="rounded-full px-2 py-1 font-medium" style={{ backgroundColor: `${subjectColor}20`, color: subjectColor }}>{campaign.primary_subject.name}</span><span>{campaign.grade.name}</span></div><h3 className="text-lg font-black">{campaign.title}</h3><p className="mt-2 flex gap-3 text-sm text-slate-600"><span className="inline-flex items-center gap-1"><MapPin className="h-4" />{campaign.missions_count} missões</span><span className="inline-flex items-center gap-1"><Clock className="h-4" />{campaign.estimated_minutes} min</span></p><div className="mt-4 flex items-center gap-3"><div className="h-2.5 flex-1 overflow-hidden rounded-full bg-sky-100"><div className="xp-fill h-full rounded-full bg-gradient-to-r from-sky-600 to-cyan-400" style={{ width: `${campaign.progress.percent}%` }} /></div><span className="text-xs font-black text-sky-800">{campaign.progress.percent}%</span></div><div className="mt-4 flex items-center justify-between"><span className="text-sm text-slate-600">{isComplete ? 'Mapa explorado' : 'Em andamento'}</span><Link className="btn-primary text-sm" href={`/campaigns/${campaign.id}`}>{isComplete ? <><CheckCircle2 className="h-4" />Ver</> : 'Continuar'}</Link></div></div></article>;
}

export function AchievementCard({ title, icon, unlocked }: { title: string; icon?: string; unlocked: boolean }) { return <article className={`achievement-card game-card relative overflow-hidden p-5 ${unlocked ? 'achievement-unlocked' : 'achievement-locked'}`}><div className="relative mb-4 grid h-14 w-14 place-items-center rounded-2xl text-2xl">{unlocked ? <><span className="absolute inset-0 rounded-2xl bg-amber-100" /><span className="relative">{icon ?? '🏅'}</span></> : <><span className="absolute inset-0 rounded-2xl border-2 border-dashed border-sky-300 bg-sky-50" /><Lock className="relative h-5 text-sky-400" /></>}</div>{unlocked && <Sparkles className="absolute right-4 top-4 h-5 w-5 text-amber-400" />}<h3 className="font-black">{title}</h3><p className="mt-1 text-sm text-slate-600">{unlocked ? 'Conquista desbloqueada' : 'Uma descoberta misteriosa aguarda você'}</p></article>; }
